sync ok ; fix on dl ; doc todo

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # possible return value from the scirpt are :
-# 0 : all ok ; 1 : cli opt ; 2 : required package are not present ; 3 : invalid path provided ; 4 : sync while dl
+# 0 : all ok ; 1 : cli opt ; 2 : required package are not present ; 3 : invalid path provided ; 4 : sync while dl ; 5 : sync while sync ; 6 : invalid ip ; 7 :
 
 # fetch script path for import
 # https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself
@@ -10,17 +10,20 @@ SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
 source $SCRIPTPATH/libs/sh_lib
 
 # static value
-LOG_PATH=$SCRIPTPATH/etc/logs/
+LOG_PATH=$SCRIPTPATH/etc/logs/sync/
 LOCK_DIR=/tmp/music_dl/sync/
 DL_LOCK_DIR=/tmp/music_dl/dl/
 
 # cli value
 SYNC_CONF_PATH=$SCRIPTPATH/etc/sync.conf
 DL_PATH=$SCRIPTPATH/Music/
+TARGET_PATH=/sdcard/Music/
+CONNECT_IP=0.0.0.0
+
 INSTALL=0
 
 USAGE="
-Usage : sync -d [path] -s [path] -l [0..3] -i -h
+Usage : sync -d [path] -s [path] -c [IP] -l [0..3] -i -h
 
 Run sync, a simple android sync script.
 
@@ -28,6 +31,9 @@ Configuration options :
 
     -d:     root path for root sync path. A full or relative path can be provide.
             Default : [$DL_PATH]
+    -c:     connect ip of the android device. Please be sure that the device support
+            adb over tcpip.
+            Default : [$CONNECT_IP]
     -s:     sync configuration file path. A full path must be provide.
             Default : [$SYNC_CONF_PATH]
 
@@ -43,9 +49,13 @@ Misc options :
 
 sync_dir() {
     local dir=$1
+    local path="$DL_PATH/$dir"
+
     # create lock
     touch $LOCK_DIR/$dir.lock
-    sleep 10
+    # echo "$path $TARGET_PATH"
+    adb-sync -n  "$path" "$TARGET_PATH"
+    #    sleep#  10
     # sync file 2>&1> log
     rm $LOCK_DIR/$dir.lock
     # remove lock
@@ -78,11 +88,13 @@ run() {
     while read f ; do
         debug "Processing $f"
 
-        if [ $f == \#* ]; then
+        if [[ "$f" =~ ^#.* ]]; then
             warn "Entry ignored"
         else
-            echo "let sync $f !"
-            (sync_dir $f) &
+            local log_file="$LOG_PATH$f.log"
+            touch $log_file
+            debug "Syncing $f ..."
+            (sync_dir $f &> $log_file) &
         fi
     done < <(cat $SYNC_CONF_PATH)
 
@@ -92,8 +104,16 @@ run() {
 }
 
 connect() {
+    local set -e
     # adb connect
-    echo "adb-sync connected"
+    info "connecting to the android device"
+    adb connect "$CONNECT_IP"
+    if [ $? -ne 0 ]; then
+        exit 6
+    fi
+
+    debug "adb-sync connected"
+
     # or exit
 }
 
@@ -106,8 +126,10 @@ setup() {
 
     debug "
     download path :          $DL_PATH
+    target root path :       $TARGET_PATH
     log path :               $LOG_PATH
     sync config file :       $SYNC_CONF_PATH
+    connect ip address :     $CONNECT_IP
     loglevel :               $LEVEL
 "
 
@@ -117,16 +139,24 @@ setup() {
         exit_if_not_installed $prg
     done
 
+    if [ -z "$CONNECT_IP" ]; then
+        error "Invalid ip address"
+        exit 5
+    fi
+
     check_if_dir_exist "$DL_PATH" "download root path"
     check_if_file_exist "$SYNC_CONF_PATH" "sync configuration file"
 
     if (find $DL_LOCK_DIR/ -mindepth 1 -print -quit 2>/dev/null | grep -q .); then
         error "Cannot sync while downloading"
         exit 4
+    elif (find $LOCK_DIR/ -mindepth 1 -print -quit 2>/dev/null | grep -q .); then
+        error "Cannot sync while syncing"
+        exit 5
     fi
 
     mkdir -p $LOCK_DIR
-
+    mkdir -p $LOG_PATH
     info "All okay let's process !"
 }
 
@@ -134,11 +164,17 @@ setup() {
 # main
 #
 
-while getopts "l:ih" o; do
+while getopts "l:c:d:ih" o; do
     case "${o}" in
         l)
             LEVEL=${OPTARG}
 	          ;;
+        c)
+            CONNECT_IP=${OPTARG} # TODO doc
+            ;;
+        d)
+            DL_PATH=${OPTARG}
+            ;;
         i)
             INSTALL=1
             ;;
